type Query {
  accountGet: User
  accountGetMfaRecoveryCodes: MfaRecoveryCodes
  accountGetPrefs: Preferences
  accountGetSession(sessionId: String!): Session
  accountListIdentities(queries: String, total: Boolean): IdentityList
  accountListLogs(queries: [String], total: Boolean): LogList
  accountListMfaFactors: MfaFactors
  accountListSessions: SessionList
  databasesGetDocument(
    databaseId: String!
    collectionId: String!
    documentId: String!
    queries: [String]
    transactionId: String
  ): Document
  databasesGetTransaction(transactionId: String!): Transaction
  databasesListDocuments(
    databaseId: String!
    collectionId: String!
    queries: [String]
    transactionId: String
    total: Boolean
    ttl: Int
  ): DocumentList
  databasesListTransactions(queries: String): TransactionList
  functionsGetExecution(functionId: String!, executionId: String!): Execution
  functionsListExecutions(functionId: String!, queries: [String], total: Boolean): ExecutionList
  localeGet: Locale
  localeListCodes: LocaleCodeList
  localeListContinents: ContinentList
  localeListCountries: CountryList
  localeListCountriesEU: CountryList
  localeListCountriesPhones: PhoneList
  localeListCurrencies: CurrencyList
  localeListLanguages: LanguageList
  storageGetFile(bucketId: String!, fileId: String!): File
  storageListFiles(bucketId: String!, queries: [String], search: String, total: Boolean): FileList
  tablesDBGetRow(
    databaseId: String!
    tableId: String!
    rowId: String!
    queries: [String]
    transactionId: String
  ): Row
  tablesDBGetTransaction(transactionId: String!): Transaction
  tablesDBListRows(
    databaseId: String!
    tableId: String!
    queries: [String]
    transactionId: String
    total: Boolean
    ttl: Int
  ): RowList
  tablesDBListTransactions(queries: String): TransactionList
  teamsGet(teamId: String!): Team
  teamsGetMembership(teamId: String!, membershipId: String!): Membership
  teamsGetPrefs(teamId: String!): Preferences
  teamsList(queries: [String], search: String, total: Boolean): TeamList
  teamsListMemberships(
    teamId: String!
    queries: [String]
    search: String
    total: Boolean
  ): MembershipList
}

type Mutation {
  accountCreate(userId: String!, email: String!, password: String!, name: String): User
  accountCreateAnonymousSession: Session
  accountCreateEmailPasswordSession(email: String!, password: String!): Session
  accountCreateEmailToken(userId: String!, email: String!, phrase: Boolean): Token
  accountCreateEmailVerification(url: String!): Token
  accountCreateJWT(duration: Int): Jwt
  accountCreateMagicURLToken(userId: String!, email: String!, url: String, phrase: Boolean): Token
  accountCreateMfaAuthenticator(type: String!): MfaType
  accountCreateMfaChallenge(factor: String!): MfaChallenge
  accountCreateMfaRecoveryCodes: MfaRecoveryCodes
  accountCreatePhoneToken(userId: String!, phone: String!): Token
  accountCreatePhoneVerification: Token
  accountCreatePushTarget(targetId: String!, identifier: String!, providerId: String): Target
  accountCreateRecovery(email: String!, url: String!): Token
  accountCreateSession(userId: String!, secret: String!): Session
  accountCreateVerification(url: String!): Token
  accountDeleteIdentity(identityId: String!): None
  accountDeleteMfaAuthenticator(type: String!): None
  accountDeletePushTarget(targetId: String!): None
  accountDeleteSession(sessionId: String!): None
  accountDeleteSessions: None
  accountUpdateEmail(email: String!, password: String!): User
  accountUpdateEmailVerification(userId: String!, secret: String!): Token
  accountUpdateMFA(mfa: Boolean!): User
  accountUpdateMagicURLSession(userId: String!, secret: String!): Session
  accountUpdateMfaAuthenticator(type: String!, otp: String!): User
  accountUpdateMfaChallenge(challengeId: String!, otp: String!): Session
  accountUpdateMfaRecoveryCodes: MfaRecoveryCodes
  accountUpdateName(name: String!): User
  accountUpdatePassword(password: String!, oldPassword: String): User
  accountUpdatePhone(phone: String!, password: String!): User
  accountUpdatePhoneSession(userId: String!, secret: String!): Session
  accountUpdatePhoneVerification(userId: String!, secret: String!): Token
  accountUpdatePrefs(prefs: Assoc!): User
  accountUpdatePushTarget(targetId: String!, identifier: String!): Target
  accountUpdateRecovery(userId: String!, secret: String!, password: String!): Token
  accountUpdateSession(sessionId: String!): Session
  accountUpdateStatus: User
  accountUpdateVerification(userId: String!, secret: String!): Token
  databasesCreateDocument(
    databaseId: String!
    documentId: String!
    collectionId: String!
    data: Json!
    permissions: [String]
    transactionId: String
  ): Document
  databasesCreateOperations(transactionId: String!, operations: [String]): Transaction
  databasesCreateTransaction(ttl: Int): Transaction
  databasesDecrementDocumentAttribute(
    databaseId: String!
    collectionId: String!
    documentId: String!
    attribute: String!
    value: Int
    min: Int
    transactionId: String
  ): Document
  databasesDeleteDocument(
    databaseId: String!
    collectionId: String!
    documentId: String!
    transactionId: String
  ): None
  databasesDeleteTransaction(transactionId: String!): None
  databasesIncrementDocumentAttribute(
    databaseId: String!
    collectionId: String!
    documentId: String!
    attribute: String!
    value: Int
    max: Int
    transactionId: String
  ): Document
  databasesUpdateDocument(
    databaseId: String!
    collectionId: String!
    documentId: String!
    data: Json
    permissions: [String]
    transactionId: String
  ): Document
  databasesUpdateTransaction(
    transactionId: String!
    commit: Boolean
    rollback: Boolean
  ): Transaction
  databasesUpsertDocument(
    databaseId: String!
    collectionId: String!
    documentId: String!
    data: Json
    permissions: [String]
    transactionId: String
  ): Document
  functionsCreateExecution(
    functionId: String!
    body: String
    async: Boolean
    path: String
    method: String
    headers: String
    scheduledAt: String
  ): Execution
  messagingCreateSubscriber(subscriberId: String!, topicId: String!, targetId: String!): Subscriber
  messagingDeleteSubscriber(topicId: String!, subscriberId: String!): None
  storageDeleteFile(bucketId: String!, fileId: String!): None
  storageUpdateFile(bucketId: String!, fileId: String!, name: String, permissions: [String]): File
  tablesDBCreateOperations(transactionId: String!, operations: [String]): Transaction
  tablesDBCreateRow(
    databaseId: String!
    rowId: String!
    tableId: String!
    data: Json!
    permissions: [String]
    transactionId: String
  ): Row
  tablesDBCreateTransaction(ttl: Int): Transaction
  tablesDBDecrementRowColumn(
    databaseId: String!
    tableId: String!
    rowId: String!
    column: String!
    value: Int
    min: Int
    transactionId: String
  ): Row
  tablesDBDeleteRow(
    databaseId: String!
    tableId: String!
    rowId: String!
    transactionId: String
  ): None
  tablesDBDeleteTransaction(transactionId: String!): None
  tablesDBIncrementRowColumn(
    databaseId: String!
    tableId: String!
    rowId: String!
    column: String!
    value: Int
    max: Int
    transactionId: String
  ): Row
  tablesDBUpdateRow(
    databaseId: String!
    tableId: String!
    rowId: String!
    data: Json
    permissions: [String]
    transactionId: String
  ): Row
  tablesDBUpdateTransaction(transactionId: String!, commit: Boolean, rollback: Boolean): Transaction
  tablesDBUpsertRow(
    databaseId: String!
    tableId: String!
    rowId: String!
    data: Json
    permissions: [String]
    transactionId: String
  ): Row
  teamsCreate(teamId: String!, name: String!, roles: [String]): Team
  teamsCreateMembership(
    teamId: String!
    email: String
    userId: String
    phone: String
    roles: [String!]!
    url: String
    name: String
  ): Membership
  teamsDelete(teamId: String!): None
  teamsDeleteMembership(teamId: String!, membershipId: String!): None
  teamsUpdateMembership(teamId: String!, membershipId: String!, roles: [String!]!): Membership
  teamsUpdateMembershipStatus(
    teamId: String!
    membershipId: String!
    userId: String!
    secret: String!
  ): Membership
  teamsUpdateName(teamId: String!, name: String!): Team
  teamsUpdatePrefs(teamId: String!, prefs: Assoc!): Preferences
}

type None {
  status: String
}

type User {
  _id: String
  _createdAt: String
  _updatedAt: String
  name: String
  password: String
  hash: String
  hashOptions: HashOptions
  registration: String
  status: Boolean
  labels: [String]
  passwordUpdate: String
  email: String
  phone: String
  emailVerification: Boolean
  phoneVerification: Boolean
  mfa: Boolean
  prefs: Preferences
  targets: [Target]
  accessedAt: String
  impersonator: Boolean
  impersonatorUserId: String
}

union HashOptions =
  | AlgoArgon2
  | AlgoScrypt
  | AlgoScryptModified
  | AlgoBcrypt
  | AlgoPhpass
  | AlgoSha
  | AlgoMd5

type AlgoArgon2 {
  type: String
  memoryCost: Int
  timeCost: Int
  threads: Int
}

type AlgoScrypt {
  type: String
  costCpu: Int
  costMemory: Int
  costParallel: Int
  length: Int
}

type AlgoScryptModified {
  type: String
  salt: String
  saltSeparator: String
  signerKey: String
}

type AlgoBcrypt {
  type: String
}

type AlgoPhpass {
  type: String
}

type AlgoSha {
  type: String
}

type AlgoMd5 {
  type: String
}

type Preferences {
  data: String
}

type Target {
  _id: String
  _createdAt: String
  _updatedAt: String
  name: String
  userId: String
  providerId: String
  providerType: String
  identifier: String
  expired: Boolean
}

type MfaRecoveryCodes {
  recoveryCodes: [String]
}

type Session {
  _id: String
  _createdAt: String
  _updatedAt: String
  userId: String
  expire: String
  provider: String
  providerUid: String
  providerAccessToken: String
  providerAccessTokenExpiry: String
  providerRefreshToken: String
  ip: String
  osCode: String
  osName: String
  osVersion: String
  clientType: String
  clientCode: String
  clientName: String
  clientVersion: String
  clientEngine: String
  clientEngineVersion: String
  deviceName: String
  deviceBrand: String
  deviceModel: String
  countryCode: String
  countryName: String
  current: Boolean
  factors: [String]
  secret: String
  mfaUpdatedAt: String
}

type IdentityList {
  total: Int
  identities: [Identity]
}

type Identity {
  _id: String
  _createdAt: String
  _updatedAt: String
  userId: String
  provider: String
  providerUid: String
  providerEmail: String
  providerAccessToken: String
  providerAccessTokenExpiry: String
  providerRefreshToken: String
}

type LogList {
  total: Int
  logs: [Log]
}

type Log {
  event: String
  userId: String
  userEmail: String
  userName: String
  mode: String
  ip: String
  time: String
  osCode: String
  osName: String
  osVersion: String
  clientType: String
  clientCode: String
  clientName: String
  clientVersion: String
  clientEngine: String
  clientEngineVersion: String
  deviceName: String
  deviceBrand: String
  deviceModel: String
  countryCode: String
  countryName: String
}

type MfaFactors {
  totp: Boolean
  phone: Boolean
  email: Boolean
  recoveryCode: Boolean
}

type SessionList {
  total: Int
  sessions: [Session]
}

scalar Assoc

scalar Json

type Document {
  data: String
  _id: String
  _sequence: String
  _collectionId: String
  _databaseId: String
  _createdAt: String
  _updatedAt: String
  _permissions: [String]
}

type Transaction {
  _id: String
  _createdAt: String
  _updatedAt: String
  status: String
  operations: Int
  expiresAt: String
}

type DocumentList {
  total: Int
  documents: [Document]
}

type TransactionList {
  total: Int
  transactions: [Transaction]
}

type Execution {
  _id: String
  _createdAt: String
  _updatedAt: String
  _permissions: [String]
  functionId: String
  deploymentId: String
  trigger: String
  status: String
  requestMethod: String
  requestPath: String
  requestHeaders: [Headers]
  responseStatusCode: Int
  responseBody: String
  responseHeaders: [Headers]
  logs: String
  errors: String
  duration: Float
  scheduledAt: String
}

type Headers {
  name: String
  value: String
}

type ExecutionList {
  total: Int
  executions: [Execution]
}

type Locale {
  ip: String
  countryCode: String
  country: String
  continentCode: String
  continent: String
  eu: Boolean
  currency: String
}

type LocaleCodeList {
  total: Int
  localeCodes: [LocaleCode]
}

type LocaleCode {
  code: String
  name: String
}

type ContinentList {
  total: Int
  continents: [Continent]
}

type Continent {
  name: String
  code: String
}

type CountryList {
  total: Int
  countries: [Country]
}

type Country {
  name: String
  code: String
}

type PhoneList {
  total: Int
  phones: [Phone]
}

type Phone {
  code: String
  countryCode: String
  countryName: String
}

type CurrencyList {
  total: Int
  currencies: [Currency]
}

type Currency {
  symbol: String
  name: String
  symbolNative: String
  decimalDigits: Int
  rounding: Float
  code: String
  namePlural: String
}

type LanguageList {
  total: Int
  languages: [Language]
}

type Language {
  name: String
  code: String
  nativeName: String
}

type Subscriber {
  _id: String
  _createdAt: String
  _updatedAt: String
  targetId: String
  target: Target
  userId: String
  userName: String
  topicId: String
  providerType: String
}

type File {
  _id: String
  bucketId: String
  _createdAt: String
  _updatedAt: String
  _permissions: [String]
  name: String
  signature: String
  mimeType: String
  sizeOriginal: Int
  chunksTotal: Int
  chunksUploaded: Int
  encryption: Boolean
  compression: String
}

type FileList {
  total: Int
  files: [File]
}

type Row {
  data: String
  _id: String
  _sequence: String
  _tableId: String
  _databaseId: String
  _createdAt: String
  _updatedAt: String
  _permissions: [String]
}

type RowList {
  total: Int
  rows: [Row]
}

type Team {
  _id: String
  _createdAt: String
  _updatedAt: String
  name: String
  total: Int
  prefs: Preferences
}

type Membership {
  _id: String
  _createdAt: String
  _updatedAt: String
  userId: String
  userName: String
  userEmail: String
  teamId: String
  teamName: String
  invited: String
  joined: String
  confirm: Boolean
  mfa: Boolean
  roles: [String]
}

type TeamList {
  total: Int
  teams: [Team]
}

type MembershipList {
  total: Int
  memberships: [Membership]
}

type Token {
  _id: String
  _createdAt: String
  userId: String
  secret: String
  expire: String
  phrase: String
}

type Jwt {
  jwt: String
}

type MfaType {
  secret: String
  uri: String
}

type MfaChallenge {
  _id: String
  _createdAt: String
  userId: String
  expire: String
}
