scalar Json
scalar Assoc
scalar InputFile

schema {
  query: Query
  mutation: Mutation
}

type Query {
  # Account
  accountGet: User
  accountGetPrefs: Preferences
  accountGetMfaRecoveryCodes: MfaRecoveryCodes
  accountGetSession(sessionId: String!): Session
  accountListIdentities(queries: String, total: Boolean): IdentityList
  accountListLogs(queries: [String], total: Boolean): LogList
  accountListMfaFactors: MfaFactors
  accountListSessions: SessionList

  # Databases
  databasesGetDocument(
    databaseId: String!
    collectionId: String!
    documentId: String!
    queries: [String]
    transactionId: String
  ): Document
  databasesGetTransaction(transactionId: String!): Transaction
  databasesListDocuments(
    databaseId: String!
    collectionId: String!
    queries: [String]
    transactionId: String
    total: Boolean
  ): DocumentList
  databasesListTransactions(queries: String): TransactionList

  # Functions
  functionsGetExecution(functionId: String!, executionId: String!): Execution
  functionsListExecutions(functionId: String!, queries: [String], total: Boolean): ExecutionList

  # Locale
  localeGet: Locale
  localeListCodes: LocaleCodeList
  localeListContinents: ContinentList
  localeListCountries: CountryList
  localeListCountriesEU: CountryList
  localeListCountriesPhones: PhoneList
  localeListCurrencies: CurrencyList
  localeListLanguages: LanguageList

  # Storage
  storageGetFile(bucketId: String!, fileId: String!): File
  storageGetFileDownload(bucketId: String!, fileId: String!, token: String): None
  storageGetFilePreview(
    bucketId: String!
    fileId: String!
    width: Int
    height: Int
    gravity: String
    quality: Int
    borderWidth: Int
    borderColor: String
    borderRadius: Int
    opacity: Float
    rotation: Int
    background: String
    output: String
    token: String
  ): None
  storageGetFileView(bucketId: String!, fileId: String!, token: String): None
  storageListFiles(bucketId: String!, queries: [String], search: String, total: Boolean): FileList

  # Teams
  teamsGet(teamId: String!): Team
  teamsGetMembership(teamId: String!, membershipId: String!): Membership
  teamsGetPrefs(teamId: String!): Preferences
  teamsList(queries: [String], search: String, total: Boolean): TeamList
  teamsListMemberships(
    teamId: String!
    queries: [String]
    search: String
    total: Boolean
  ): MembershipList
}

type Mutation {
  # Account
  accountCreate(userId: String!, email: String!, password: String!, name: String): User
  accountCreateAnonymousSession: Session
  accountCreateEmailPasswordSession(email: String!, password: String!): Session
  accountCreateJWT: Jwt
  accountCreateEmailToken(userId: String!, email: String!, phrase: Boolean): Token
  accountCreateMagicURLToken(userId: String!, email: String!, url: String, phrase: Boolean): Token
  accountCreateMfaAuthenticator(type: String!): MfaType
  accountCreateMfaChallenge(factor: String!): MfaChallenge
  accountCreateMfaRecoveryCodes: MfaRecoveryCodes
  accountCreatePhoneToken(userId: String!, phone: String!): Token
  accountCreatePhoneVerification: Token
  accountCreateRecovery(email: String!, url: String!): Token
  accountCreateSession(userId: String!, secret: String!): Session
  accountCreateVerification(url: String!): Token
  accountCreateEmailVerification(url: String!): Token
  accountDeleteIdentity(identityId: String!): None
  accountDeleteMfaAuthenticator(type: String!): None
  accountDeleteSession(sessionId: String!): None
  accountDeleteSessions: None
  accountUpdateEmail(email: String!, password: String!): User
  accountUpdateMagicURLSession(userId: String!, secret: String!): Session
  accountUpdateMFA(mfa: Boolean!): User
  accountUpdateMfaAuthenticator(type: String!, otp: String!): User
  accountUpdateMfaChallenge(challengeId: String!, otp: String!): Session
  accountUpdateMfaRecoveryCodes: MfaRecoveryCodes
  accountUpdateName(name: String!): User
  accountUpdatePassword(password: String!, oldPassword: String): User
  accountUpdatePhone(phone: String!, password: String!): User
  accountUpdatePhoneSession(userId: String!, secret: String!): Session
  accountUpdatePhoneVerification(userId: String!, secret: String!): Token
  accountUpdatePrefs(prefs: Assoc!): User
  accountUpdateRecovery(userId: String!, secret: String!, password: String!): Token
  accountUpdateSession(sessionId: String!): Session
  accountUpdateVerification(userId: String!, secret: String!): Token
  accountUpdateEmailVerification(userId: String!, secret: String!): Token
  accountCreatePushTarget(targetId: String!, identifier: String!, providerId: String): Target
  accountUpdatePushTarget(targetId: String!, identifier: String!): Target
  accountDeletePushTarget(targetId: String!): None
  accountUpdateStatus: User

  # Databases
  databasesCreateDocument(
    databaseId: String!
    documentId: String!
    collectionId: String!
    data: Json!
    permissions: [String]
    transactionId: String
  ): Document
  databasesDeleteDocument(
    databaseId: String!
    collectionId: String!
    documentId: String!
    transactionId: String
  ): None
  databasesUpdateDocument(
    databaseId: String!
    collectionId: String!
    documentId: String!
    data: Json
    permissions: [String]
    transactionId: String
  ): Document
  databasesUpsertDocument(
    databaseId: String!
    collectionId: String!
    documentId: String!
    data: Json!
    permissions: [String]
    transactionId: String
  ): Document
  databasesIncrementDocumentAttribute(
    databaseId: String!
    collectionId: String!
    documentId: String!
    attribute: String!
    value: Int
    max: Int
    transactionId: String
  ): Document
  databasesDecrementDocumentAttribute(
    databaseId: String!
    collectionId: String!
    documentId: String!
    attribute: String!
    value: Int
    min: Int
    transactionId: String
  ): Document
  databasesCreateTransaction(ttl: Int): Transaction
  databasesCreateOperations(transactionId: String!, operations: [String]): Transaction
  databasesUpdateTransaction(
    transactionId: String!
    commit: Boolean
    rollback: Boolean
  ): Transaction
  databasesDeleteTransaction(transactionId: String!): None

  # Functions
  functionsCreateExecution(
    functionId: String!
    body: String
    async: Boolean
    path: String
    method: String
    headers: String
    scheduledAt: String
  ): Execution

  # Messaging
  messagingCreateSubscriber(subscriberId: String!, topicId: String!, targetId: String!): Subscriber
  messagingDeleteSubscriber(topicId: String!, subscriberId: String!): None

  # Storage
  storageCreateFile(
    bucketId: String!
    fileId: String!
    file: InputFile!
    permissions: [String]
  ): File
  storageUpdateFile(bucketId: String!, fileId: String!, name: String, permissions: [String]): File
  storageDeleteFile(bucketId: String!, fileId: String!): None

  # Teams
  teamsCreate(teamId: String!, name: String!, roles: [String]): Team
  teamsCreateMembership(
    teamId: String!
    email: String
    userId: String
    phone: String
    roles: [String!]!
    url: String
    name: String
  ): Membership
  teamsDelete(teamId: String!): None
  teamsDeleteMembership(teamId: String!, membershipId: String!): None
  teamsUpdateMembership(teamId: String!, membershipId: String!, roles: [String!]!): Membership
  teamsUpdateMembershipStatus(
    teamId: String!
    membershipId: String!
    userId: String!
    secret: String!
  ): Membership
  teamsUpdateName(teamId: String!, name: String!): Team
  teamsUpdatePrefs(teamId: String!, prefs: Assoc!): Preferences
}

type User {
  _id: String
  _createdAt: String
  _updatedAt: String
  name: String
  registration: String
  status: Boolean
  labels: [String]
  email: String
  phone: String
  emailVerification: Boolean
  phoneVerification: Boolean
  mfa: Boolean
  accessedAt: String
  prefs: Preferences
  targets: [Target]
}

type Target {
  _id: String
  _createdAt: String
  _updatedAt: String
  name: String
  userId: String
  providerId: String
  providerType: String
  identifier: String
  expired: Boolean
}

type Preferences {
  data: Json
}

type Session {
  _id: String
  _createdAt: String
  _updatedAt: String
  userId: String
  expire: String
  provider: String
  providerUid: String
  providerAccessToken: String
  providerAccessTokenExpiry: String
  providerRefreshToken: String
  ip: String
  osCode: String
  osName: String
  osVersion: String
  clientType: String
  clientCode: String
  clientName: String
  clientVersion: String
  clientEngine: String
  clientEngineVersion: String
  deviceName: String
  deviceBrand: String
  deviceModel: String
  countryCode: String
  countryName: String
  current: Boolean
  factors: [String]
  secret: String
  mfaUpdatedAt: String
}

type SessionList {
  total: Int
  sessions: [Session]
}

type DocumentList {
  total: Int
  documents: [Document]
}

type Document {
  _id: String
  _collectionId: String
  _databaseId: String
  _createdAt: String
  _updatedAt: String
  _permissions: [String]
  data: Json
}

type Token {
  _id: String
  _createdAt: String
  userId: String
  secret: String
  expire: String
  phrase: String
}

type ExecutionList {
  total: Int
  executions: [Execution]
}

type Execution {
  _id: String
  _createdAt: String
  _updatedAt: String
  _permissions: [String]
  functionId: String
  deploymentId: String
  trigger: String
  status: String
  requestMethod: String
  requestPath: String
  requestHeaders: [Headers]
  responseStatusCode: Int
  responseBody: String
  responseHeaders: [Headers]
  logs: String
  errors: String
  duration: Float
  scheduledAt: String
}

type Headers {
  name: String
  value: String
}

type None {
  status: String
}

type Jwt {
  jwt: String
}

type IdentityList {
  total: Int
  identities: [Identity]
}

type Identity {
  _id: String
  _createdAt: String
  _updatedAt: String
  userId: String
  provider: String
  providerUid: String
  providerEmail: String
  providerAccessToken: String
  providerAccessTokenExpiry: String
  providerRefreshToken: String
}

type LogList {
  total: Int
  logs: [Log]
}

type Log {
  event: String
  userId: String
  userEmail: String
  userName: String
  mode: String
  ip: String
  time: String
  osCode: String
  osName: String
  osVersion: String
  clientType: String
  clientCode: String
  clientName: String
  clientVersion: String
  clientEngine: String
  clientEngineVersion: String
  deviceName: String
  deviceBrand: String
  deviceModel: String
  countryCode: String
  countryName: String
}

type MfaType {
  secret: String
  uri: String
}

type MfaChallenge {
  _id: String
  _createdAt: String
  userId: String
  expire: String
}

type MfaFactors {
  totp: Boolean
  phone: Boolean
  email: Boolean
  recoveryCode: Boolean
}

type MfaRecoveryCodes {
  recoveryCodes: [String]
}

type Subscriber {
  _id: String
  _createdAt: String
  _updatedAt: String
  targetId: String
  target: Target
  userId: String
  userName: String
  topicId: String
  providerType: String
}

type Locale {
  ip: String
  countryCode: String
  country: String
  continentCode: String
  continent: String
  eu: Boolean
  currency: String
}

type LocaleCode {
  code: String
  name: String
}

type LocaleCodeList {
  total: Int
  localeCodes: [LocaleCode]
}

type Continent {
  name: String
  code: String
}

type ContinentList {
  total: Int
  continents: [Continent]
}

type Country {
  name: String
  code: String
}

type CountryList {
  total: Int
  countries: [Country]
}

type Phone {
  code: String
  countryCode: String
  countryName: String
}

type PhoneList {
  total: Int
  phones: [Phone]
}

type Currency {
  symbol: String
  name: String
  symbolNative: String
  decimalDigits: Int
  rounding: Float
  code: String
  namePlural: String
}

type CurrencyList {
  total: Int
  currencies: [Currency]
}

type Language {
  name: String
  code: String
  nativeName: String
}

type LanguageList {
  total: Int
  languages: [Language]
}

type File {
  _id: String
  bucketId: String
  _createdAt: String
  _updatedAt: String
  _permissions: [String]
  name: String
  signature: String
  mimeType: String
  sizeOriginal: Int
  chunksTotal: Int
  chunksUploaded: Int
}

type FileList {
  total: Int
  files: [File]
}

type Team {
  _id: String
  _createdAt: String
  _updatedAt: String
  name: String
  total: Int
  prefs: Preferences
}

type TeamList {
  total: Int
  teams: [Team]
}

type Membership {
  _id: String
  _createdAt: String
  _updatedAt: String
  userId: String
  userName: String
  userEmail: String
  teamId: String
  teamName: String
  invited: String
  joined: String
  confirm: Boolean
  mfa: Boolean
  roles: [String]
}

type MembershipList {
  total: Int
  memberships: [Membership]
}

type Transaction {
  _id: String
  _createdAt: String
  _updatedAt: String
  status: String
  operations: Int
  expiresAt: String
}

type TransactionList {
  total: Int
  transactions: [Transaction]
}
